### ISSUE TITLE
Fails to build on FreeBSD 11.1

### ISSUE THREAD

**Issue by adam12** [boazsegev/iodine#35]
First off - thanks for this great app server, and your work to push the Rack Upgrade standard forward!

I'm having issues building this gem on FreeBSD. I've seen reports that we need to use a `#undef _POSIX_C_SOURCE` which I tried to no-avail.

Just out of curiosity, I went back through the released versions and the latest one that I could build was 0.2.17. Some of them failed with the following message, and some of them complained about ` error: incomplete definition of type 'struct sockaddr_in'`.

```
current directory: /usr/local/lib/ruby/gems/2.3.0/gems/iodine-0.5.1/ext/iodine
/usr/local/bin/ruby -r ./siteconf20180511-34785-1kh3kyg.rb extconf.rb
checking for kevent()... yes
checking for clang... yes
testing clang for stdatomic support...
using clang compiler v. 4.2.1
.
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-freebsd-11/2.3.0-static/iodine-0.5.1/mkmf.log

current directory: /usr/local/lib/ruby/gems/2.3.0/gems/iodine-0.5.1/ext/iodine
make "DESTDIR=" clean

current directory: /usr/local/lib/ruby/gems/2.3.0/gems/iodine-0.5.1/ext/iodine
make "DESTDIR="
compiling defer.c
compiling evio.c
compiling evio_callbacks.c
compiling evio_epoll.c
compiling evio_kqueue.c
In file included from evio_kqueue.c:23:
/usr/include/sys/event.h:61:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short         flags;
        ^
/usr/include/sys/event.h:62:2: error: unknown type name 'u_int'
        u_int           fflags;
        ^
2 errors generated.
*** Error code 1

Stop.
make: stopped in /usr/local/lib/ruby/gems/2.3.0/gems/iodine-0.5.1/ext/iodine

make failed, exit code 1
```

```
# uname -a
FreeBSD  11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```

Let me know if you need any more information or I can help debug in any way. Cheers.

**Comment by adam12** [comment]
Here's a patch that get's it to build. I haven't written C in an extremely long time, so salt to taste.

```diff
diff --git a/ext/iodine/evio.h b/ext/iodine/evio.h
index 53c2fd4..ff0e048 100644
--- a/ext/iodine/evio.h
+++ b/ext/iodine/evio.h
@@ -7,6 +7,7 @@ Feel free to copy, use and enjoy according to the license provided.
 #ifndef H_FACIL_EVIO_H
 #include <stdint.h>
 #include <stdlib.h>
+#include <sys/param.h>

 /**
 This is an `epoll` / `kqueue` ONE-SHOT polling wrapper, allowing for portability
diff --git a/ext/iodine/http.c b/ext/iodine/http.c
index 0d57f04..bd6d422 100644
--- a/ext/iodine/http.c
+++ b/ext/iodine/http.c
@@ -15,12 +15,17 @@ Feel free to copy, use and enjoy according to the license provided.
 #include <fcntl.h>
 #include <signal.h>
 #include <string.h>
+#include <sys/socket.h>
 #include <sys/stat.h>
 #include <sys/types.h>
 #include <unistd.h>

 #include "fio_mem.h"

+#if defined(__FreeBSD__)
+#include <netinet/in.h>
+#endif
+
 /* *****************************************************************************
 Patch for OSX version < 10.12 from https://stackoverflow.com/a/9781275/4025095
 ***************************************************************************** */
diff --git a/ext/iodine/iodine_http.c b/ext/iodine/iodine_http.c
index 95e8786..da1e00c 100644
--- a/ext/iodine/iodine_http.c
+++ b/ext/iodine/iodine_http.c
@@ -17,6 +17,10 @@ Feel free to copy, use and enjoy according to the license provided.
 #include <string.h>
 #include <sys/socket.h>

+#if defined(__FreeBSD__)
+#include <netinet/in.h>
+#endif
+
 /* *****************************************************************************
 Available Globals
 ***************************************************************************** */
```

**Comment by boazsegev** [comment]
Hi @adam12 ,

Thank you so much for opening this issue and for the suggested patch.

I have to admit it was a surprise to read this issue, since I installed iodine 0.4.x on FreeBSD before (but I think it was FreeBSD 12).

The funny thing is that I am just now testing a patch for the issue (I'm having a hard time getting the FreeBSD VM to listen to me, it brings back memories)...

Searching through the documentation it seems to be related to the order in which the include files are listed (rather than a missing include file). Maybe this is what happens when clang-format automatically sorts the include files alphabetically.

Since you already tested your approach I'll probably adopt it... I just want to manage and test the solutions myself 😅.

BTW

Since you mentioned the new draft for a Rack WebSockets/SSE standard, you might have noticed that the Rack community required a change to the API (in order to avoid the use of `extend`, a client object was added).

Additional changes to the Pub/Sub API were made to accommodate possible future ActionCable integration.

You can start using the new API today by installing from [the 0.6.0 development branch](https://github.com/boazsegev/iodine/tree/0.6-stripped). It's still fairly fresh and not as well tested, so it might be glitchy at times, but I expect to have a stable version in a week or two.

This will allow you to get a head start on using the new API.

**Comment by boazsegev** [comment]
I released version 0.5.2 with a fix. The fix should also apply to the 0.6.0 development branch (if you plan to use it).

Thanks again for opening the issue and the patch! 🎉🙏🏻

**Comment by adam12** [comment]
> I released version 0.5.2 with a fix. 

Worked a treat. Much thanks :)
